package com.fmc.model;

import java.math.BigDecimal;

public class UserAuto {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BASE_USER.ID
     *
     * @mbggenerated
     */
    private BigDecimal id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BASE_USER.USER_NAME
     *
     * @mbggenerated
     */
    private String userName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BASE_USER.USER_PWD
     *
     * @mbggenerated
     */
    private String userPwd;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BASE_USER.ID
     *
     * @return the value of BASE_USER.ID
     *
     * @mbggenerated
     */
    public BigDecimal getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BASE_USER.ID
     *
     * @param id the value for BASE_USER.ID
     *
     * @mbggenerated
     */
    public void setId(BigDecimal id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BASE_USER.USER_NAME
     *
     * @return the value of BASE_USER.USER_NAME
     *
     * @mbggenerated
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BASE_USER.USER_NAME
     *
     * @param userName the value for BASE_USER.USER_NAME
     *
     * @mbggenerated
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BASE_USER.USER_PWD
     *
     * @return the value of BASE_USER.USER_PWD
     *
     * @mbggenerated
     */
    public String getUserPwd() {
        return userPwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BASE_USER.USER_PWD
     *
     * @param userPwd the value for BASE_USER.USER_PWD
     *
     * @mbggenerated
     */
    public void setUserPwd(String userPwd) {
        this.userPwd = userPwd == null ? null : userPwd.trim();
    }
}