package com.fmc.dao.dept;

import com.fmc.model.dept.Dept;
import java.math.BigDecimal;
import java.util.List;

public interface DeptMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_DEPT
     *
     * @mbggenerated Fri Jul 20 18:36:05 CST 2018
     */
    int deleteByPrimaryKey(BigDecimal deptId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_DEPT
     *
     * @mbggenerated Fri Jul 20 18:36:05 CST 2018
     */
    int insert(Dept record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_DEPT
     *
     * @mbggenerated Fri Jul 20 18:36:05 CST 2018
     */
    Dept selectByPrimaryKey(BigDecimal deptId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_DEPT
     *
     * @mbggenerated Fri Jul 20 18:36:05 CST 2018
     */
    List<Dept> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_DEPT
     *
     * @mbggenerated Fri Jul 20 18:36:05 CST 2018
     */
    int updateByPrimaryKey(Dept record);
}