package com.fmc.model.dept;

import java.math.BigDecimal;
import java.util.Date;

public class Dept {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_DEPT.DEPT_ID
     *
     * @mbggenerated Fri Jul 20 18:36:05 CST 2018
     */
    private BigDecimal deptId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_DEPT.DEPT_NAME
     *
     * @mbggenerated Fri Jul 20 18:36:05 CST 2018
     */
    private String deptName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_DEPT.CREATE_USER
     *
     * @mbggenerated Fri Jul 20 18:36:05 CST 2018
     */
    private BigDecimal createUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_DEPT.CREATE_DATE
     *
     * @mbggenerated Fri Jul 20 18:36:05 CST 2018
     */
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_DEPT.UPDATE_DATE
     *
     * @mbggenerated Fri Jul 20 18:36:05 CST 2018
     */
    private Date updateDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_DEPT.CREAT_USER_NAME
     *
     * @mbggenerated Fri Jul 20 18:36:05 CST 2018
     */
    private String creatUserName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_DEPT.DEPT_ID
     *
     * @return the value of SYS_DEPT.DEPT_ID
     *
     * @mbggenerated Fri Jul 20 18:36:05 CST 2018
     */
    public BigDecimal getDeptId() {
        return deptId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_DEPT.DEPT_ID
     *
     * @param deptId the value for SYS_DEPT.DEPT_ID
     *
     * @mbggenerated Fri Jul 20 18:36:05 CST 2018
     */
    public void setDeptId(BigDecimal deptId) {
        this.deptId = deptId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_DEPT.DEPT_NAME
     *
     * @return the value of SYS_DEPT.DEPT_NAME
     *
     * @mbggenerated Fri Jul 20 18:36:05 CST 2018
     */
    public String getDeptName() {
        return deptName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_DEPT.DEPT_NAME
     *
     * @param deptName the value for SYS_DEPT.DEPT_NAME
     *
     * @mbggenerated Fri Jul 20 18:36:05 CST 2018
     */
    public void setDeptName(String deptName) {
        this.deptName = deptName == null ? null : deptName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_DEPT.CREATE_USER
     *
     * @return the value of SYS_DEPT.CREATE_USER
     *
     * @mbggenerated Fri Jul 20 18:36:05 CST 2018
     */
    public BigDecimal getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_DEPT.CREATE_USER
     *
     * @param createUser the value for SYS_DEPT.CREATE_USER
     *
     * @mbggenerated Fri Jul 20 18:36:05 CST 2018
     */
    public void setCreateUser(BigDecimal createUser) {
        this.createUser = createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_DEPT.CREATE_DATE
     *
     * @return the value of SYS_DEPT.CREATE_DATE
     *
     * @mbggenerated Fri Jul 20 18:36:05 CST 2018
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_DEPT.CREATE_DATE
     *
     * @param createDate the value for SYS_DEPT.CREATE_DATE
     *
     * @mbggenerated Fri Jul 20 18:36:05 CST 2018
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_DEPT.UPDATE_DATE
     *
     * @return the value of SYS_DEPT.UPDATE_DATE
     *
     * @mbggenerated Fri Jul 20 18:36:05 CST 2018
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_DEPT.UPDATE_DATE
     *
     * @param updateDate the value for SYS_DEPT.UPDATE_DATE
     *
     * @mbggenerated Fri Jul 20 18:36:05 CST 2018
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_DEPT.CREAT_USER_NAME
     *
     * @return the value of SYS_DEPT.CREAT_USER_NAME
     *
     * @mbggenerated Fri Jul 20 18:36:05 CST 2018
     */
    public String getCreatUserName() {
        return creatUserName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_DEPT.CREAT_USER_NAME
     *
     * @param creatUserName the value for SYS_DEPT.CREAT_USER_NAME
     *
     * @mbggenerated Fri Jul 20 18:36:05 CST 2018
     */
    public void setCreatUserName(String creatUserName) {
        this.creatUserName = creatUserName == null ? null : creatUserName.trim();
    }
}