package com.fmc.dao;

import com.fmc.model.UserAuto;
import com.fmc.model.UserAutoExample;
import org.apache.ibatis.annotations.Param;

import java.math.BigDecimal;
import java.util.List;

public interface UserAutoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BASE_USER
     *
     * @mbggenerated
     */
    int countByExample(UserAutoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BASE_USER
     *
     * @mbggenerated
     */
    int deleteByExample(UserAutoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BASE_USER
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(BigDecimal id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BASE_USER
     *
     * @mbggenerated
     */
    int insert(UserAuto record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BASE_USER
     *
     * @mbggenerated
     */
    int insertSelective(UserAuto record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BASE_USER
     *
     * @mbggenerated
     */
    List<UserAuto> selectByExample(UserAutoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BASE_USER
     *
     * @mbggenerated
     */
    UserAuto selectByPrimaryKey(BigDecimal id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BASE_USER
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") UserAuto record, @Param("example") UserAutoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BASE_USER
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") UserAuto record, @Param("example") UserAutoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BASE_USER
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(UserAuto record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BASE_USER
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(UserAuto record);
}